export const GETDATAREQ = "GETDATAREQ";
export const GETDATASUCESS = "GETDATASUCESS";
export const GETDATAFAILURE = "GETDATAFAILURE"

export const CREATEWORKFLOWREQ = "CREATEWORKFLOWREQ";
export const CREATEWORKFLOWSUCESS = "CREATEWORKFLOWSUCESS";
export const CREATEWORKFLOWFAILURE = "CREATEWORKFLOWFAILURE";
