export const GETDATAREQ = "GETDATAREQ";
export const GETDATASUCESS = "GETDATASUCESS";
export const GETDATAFAILURE = "GETDATAFAILURE"

export const CREATEWORKFLOWREQ = "CREATEWORKFLOWREQ";
export const CREATEWORKFLOWSUCESS = "CREATEWORKFLOWSUCESS";
export const CREATEWORKFLOWFAILURE = "CREATEWORKFLOWFAILURE";


export const LOGINPOSTREQ = "LOGINPOSTREQ";
export const LOGINPOSTSUCESS = "LOGINPOSTSUCESS";
export const LOGINPOSTFAILURE = "LOGINPOSTFAILURE"

export const SIGNUPREQ = "SIGNUPREQ";
export const SIGNUPSUCESS = "SIGNUPSUCESS";
export const SIGNUPFAILURE = "SIGNUPFAILURE";


export const DELETEFLOWREQ = "DELETEFLOWREQ";
export const DELETEFLOWSUCESS = "DELETEFLOWSUCESS";
export const DELETEFLOWFAILURE = "DELETEFLOWFAILURE";
